# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
# https://github.com/docker/dockercloud-agent/blob/master/agent/config.go#L173-L179

- name: Stop dockercloud agent
  service:
    name: dockercloud-agent
    state: stopped
  become: true

- name: Set docker host
  command: "dockercloud-agent set DockerHost={{ dockercloud_dockerhost }}"
  become: true

- name: Set host
  command: "dockercloud-agent set Host={{ dockercloud_host }}"
  become: true

- name: Set token
  command: "dockercloud-agent set Token={{ dockercloud_token }}"
  become: true

- name: Set options
  command: "dockercloud-agent set DockerOpts={{ dockercloud_docker_options }}"
  become: true

- name: Start/enable dockercloud agent
  service:
    name: dockercloud-agent
    state: started
    enabled: yes
  become: true
